### ISSUE TITLE
failure to load parameters?

### ISSUE THREAD

**Issue by nsteinme** [dendritic/signals#8]
It seems that when I open an experiment in mc, it does not populate the parameters section of the gui - I see only def function in global and num repeats in conditional. This is for experiment files like randomWorld that used to work. It seems to happen on both bigrig and my rig. There is no error message so far as I can see. 

Sorry if this isn't a signals issue per se?

**Comment by dendritic** [comment]
Have you clicked load default parameters?

**Comment by nsteinme** [comment]
ah... that is probably it. I forgot you had to do that. sorry...
